yarnPath: .yarn/releases/yarn-4.3.0.cjs
nodeLinker: node-modules

packageExtensions:
  '@intlify/vite-plugin-vue-i18n@*':
    dependencies:
      vite: '*'
  quasar@*:
    peerDependencies:
      vue: ^3.0.0
